AWSTemplateFormatVersion: '2010-09-09'
Description: AC heater user interface
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Runtime: python3.7
    CodeUri: lambdas

Resources:
  WebServer:
    Type: AWS::Serverless::Function
    Properties:
      Handler: handler.handler
      Policies:
        - !Ref IoTAccessPolicy
      Events:
        Web:
          Type: HttpApi

  
